name: kenet_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  bloc: ^8.1.1
  smooth_page_indicator: ^1.2.0+3
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  flutter_slidable: ^1.2.0
  pdf: ^3.8.4
  printing: ^5.13.2 # Updated to the latest version
  image: ^4.1.0 # Required for image manipulation if you want to add the signature
  http: ^1.0.0
  signature: ^5.5.0
  intl: ^0.17.0

  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.1
  barcode_scan2: ^4.3.3
  excel: ^2.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  file_picker: ^5.2.2
  open_file: ^3.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  usb_serial: ^0.5.0
  url_launcher: ^6.1.10
  audioplayers: ^6.1.0
  flutter_email_sender: ^5.0.2
  badges: ^3.1.0
  speech_to_text: ^7.0.0
  flutter_secure_storage: ^5.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_animated_dialog: ^2.0.1
  shared_preferences: ^2.0.11
  http_parser: ^4.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Declare assets here
  assets:
    - assets/images/logo.png
    - assets/images/kenet_stamp.png
    - assets/icons/user_icon.png
    - assets/icons/password_icon.png
    - assets/icons/icon.png
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3
